spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/momentum}
    username: ${SPRING_DATASOURCE_USERNAME:momentum}
    password: ${SPRING_DATASOURCE_PASSWORD:momentum}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
