spring:
  application:
    name: momentum-ingest-api
  datasource:
    url: jdbc:h2:mem:momentum-ingest;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

server:
  port: 8081

management:
  server:
    port: 9081
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}
