global:
  scrape_interval: 15s

scrape_configs:
  - job_name: momentum-api
    metrics_path: /prometheus
    static_configs:
      - targets: ["api:9080"]

  - job_name: momentum-ingest-api
    metrics_path: /prometheus
    static_configs:
      - targets: ["ingest:9081"]
